name: Pipeline sur push/merge vers main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Exemple de tâche
        run: echo "Le pipeline s'est déclenché suite à un push ou merge sur main"
        
      - name: Autre tâche
        run: echo "Ajoutez ici vos commandes de build/déploiement"