name: PHP CS Validation
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --dry-run --diff --using-cache=no