name: PHP-CS AutoFix
on: pull_request

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0  # Nécessaire pour les commits

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: php-cs-fixer, cs2pr

      - name: Dry run first (annotation des erreurs)
        run: php-cs-fixer fix --dry-run --diff --format=checkstyle | cs2pr

      - name: Apply fixes
        run: php-cs-fixer fix --diff

      - name: Commit fixes
        if: success() && steps.fixes.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🔧 PHP-CS-Fixer automatic fixes'
          branch: ${{ github.head_ref }}