name: PHP Quality Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  php-lint:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr

      - name: Run PHP Syntax Check
        run: |
          find . -type f -name '*.php' -exec php -l {} \; | grep -v 'No syntax errors detected'

  php-cs-fixer:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    needs: php-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php --dry-run --diff --allow-risky=yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Annotate results
        if: ${{ failure() }}
        run: |
          php-cs-fixer fix --dry-run --format=checkstyle | cs2pr