name: PHP Quality Gate

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  php-syntax:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Run PHP Syntax Check
        uses: mlocati/check-php-syntax@v1
        with:
          directory: .
          exclude: 'vendor/'
          fail-on-warnings: true

  php-cs-fixer:
    name: PHP Code Standards
    runs-on: ubuntu-latest
    needs: php-syntax
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP-CS-Fixer
        run: composer require --dev friendsofphp/php-cs-fixer

      - name: Run PHP-CS-Fixer
        run: |
          ./vendor/bin/php-cs-fixer fix --dry-run --diff \
            --allow-risky=yes \
            --config=.php-cs-fixer.dist.php \
            --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
