name: PHP Quality Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ main ]

jobs:
  php-syntax-check:
    name: PHP Syntax Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Find PHP files
        id: find-php
        run: |
          find . -type f -name '*.php' \
            -not -path './vendor/*' \
            -not -path './node_modules/*' \
            -printf '%P\n' > php_files.txt
          echo "files=$(cat php_files.txt | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Validate PHP syntax
        run: |
          while IFS= read -r file; do
